#ifndef __M__LEARNING__SCALE__DOUBLE__
#define __M__LEARNING__SCALE__DOUBLE__
#include<mlearning_matrix.h>
mlearning_mat_double* mlearning_scale_double(char*dataset_file_name,mlearning_row_vec_string*columns_to_scale,char*parameters_file_name,char*algorithm,mlearning_mat_double*scaled_matrix);
mlearning_mat_double* mlearning_scale_double_with_given_parameters(char*dataset_file_name,char*parameters_file_name,char*algorithm,mlearning_mat_double*scaled_matrix);
mlearning_mat_double * mlearning_scale_double_min_max(mlearning_mat_double*matrix,index_t start_row_index,index_t start_column_index,index_t end_row_index,index_t end_column_index,mlearning_mat_double** min_max_matrix,mlearning_mat_double*scaled_matrix);
mlearning_mat_double * mlearning_scale_double_with_given_min_max(mlearning_mat_double*matrix,index_t start_row_index,index_t start_column_index,index_t end_row_index,index_t end_column_index,mlearning_mat_double*min_max_matrix,mlearning_mat_double*scaled_matrix);
mlearning_mat_double* mlearning_scale_double_z_score(mlearning_mat_double*matrix,index_t start_row_index,index_t start_column_index,index_t end_row_index,index_t end_column_index,mlearning_mat_double**mean_standard_deviation_matrix,mlearning_mat_double*scaled_matrix);
mlearning_mat_double* mlearning_scale_double_z_score_with_given_mean_standard_deviation(mlearning_mat_double*matrix,index_t start_row_index,index_t start_column_index,index_t end_row_index,index_t end_column_index,mlearning_mat_double* mean_standard_deviation_matrix,mlearning_mat_double*scaled_matrix);
mlearning_column_vec_double*mlearning_scale_column_vec_double_with_given_min_max(mlearning_column_vec_double*vector,index_t from_index,index_t to_index,mlearning_mat_double*min_max_matrix,mlearning_column_vec_double*scaled_vector);
mlearning_row_vec_double*mlearning_scale_row_vec_double_with_given_min_max(mlearning_row_vec_double*vector,index_t from_index,index_t to_index,mlearning_mat_double*min_max_matrix,mlearning_row_vec_double*scaled_vector);
#endif